package model

import "context"

// Message represents a single conversational turn.
// Tool calls emitted by the assistant are kept on ToolCalls.
type Message struct {
	Role      string
	Content   string
	ToolCalls []ToolCall
}

// ToolCall captures a function-style invocation generated by the model.
type ToolCall struct {
	ID        string
	Name      string
	Arguments map[string]any
}

// ToolDefinition describes a callable function exposed to the model.
type ToolDefinition struct {
	Name        string
	Description string
	Parameters  map[string]any
}

// Request drives a single model completion.
type Request struct {
	Messages    []Message
	Tools       []ToolDefinition
	System      string
	Model       string
	SessionID   string
	MaxTokens   int
	Temperature *float64
}

// Usage reports token accounting for a completion.
type Usage struct {
	InputTokens         int
	OutputTokens        int
	TotalTokens         int
	CacheReadTokens     int
	CacheCreationTokens int
}

// Response wraps the final assistant message and accounting.
type Response struct {
	Message    Message
	Usage      Usage
	StopReason string
}

// StreamResult delivers incremental updates during streaming calls.
type StreamResult struct {
	Delta    string
	ToolCall *ToolCall
	Final    bool
	Response *Response
}

// StreamHandler consumes streaming updates in order.
type StreamHandler func(StreamResult) error

// Model is the provider-agnostic interface used by the agent runtime.
type Model interface {
	Complete(ctx context.Context, req Request) (*Response, error)
	CompleteStream(ctx context.Context, req Request, cb StreamHandler) error
}
